### ISSUE TITLE
source目录下包含html文档导致生成出错

### ISSUE THREAD

**Issue by ttimasdf** [wzpan/hexo-theme-wixo#11]
在source目录下新建了一个404.html，内容是普通的meta跳转
```html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="refresh" content="0; url=/404/">
</head>
<body></body>
</html>
```
使用 `hexo g` 生成时，会报错
```
INFO  Files loaded in 451 ms
Unhandled rejection TypeError: /private/tmp/test/themes/wixo/layout/page.ejs:1
 >> 1| <%- partial('_partial/article', {item: page, post: false}) %>

/private/tmp/test/themes/wixo/layout/_partial/article.ejs:25
    23| 	  <div>
    24|   		<center>
 >> 25| 		  <%- partial('post/pagination', {page: item}) %>
    26| 		</center>
    27| 	  </div>
    28| 	  

/private/tmp/test/themes/wixo/layout/_partial/post/pagination.ejs:8
    6| 	<% var is_cur = false %>
    7| 	<% site.posts.sort('date', -1).each(function(post){ %>
 >> 8| 		<% if (post.title == page.title){ %>
    9| 			<% is_cur = true %>
    10| 			<% prev_post = last_post %>
    11| 		<% } else if (is_cur == false && ((post.categories.length == 0 && page.categories.length ==0) || (post.categories.length > 0 && page.categories.length > 0 && post.categories.data[0]._id == page.categories.data[0]._id))) { %>

Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (/private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:713)
    at Query.forEach (/private/tmp/test/node_modules/hexo/node_modules/warehouse/lib/query.js:63:5)
    at eval (eval at <anonymous> (/private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:333)
    at eval (eval at <anonymous> (/private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2440)
    at /private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/private/tmp/test/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Render.renderSync (/private/tmp/test/node_modules/hexo/lib/hexo/render.js:87:23)
    at View.renderSync (/private/tmp/test/node_modules/hexo/lib/theme/view.js:50:29)
    at Object.partial (/private/tmp/test/node_modules/hexo/lib/plugins/helper/partial.js:42:19)
    at eval (eval at <anonymous> (/private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1059)
    at eval (eval at <anonymous> (/private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1203)
    at /private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/private/tmp/test/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Render.renderSync (/private/tmp/test/node_modules/hexo/lib/hexo/render.js:87:23)
    at View.renderSync (/private/tmp/test/node_modules/hexo/lib/theme/view.js:50:29)
    at Object.partial (/private/tmp/test/node_modules/hexo/lib/plugins/helper/partial.js:42:19)
    at eval (eval at <anonymous> (/private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:100)
    at /private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/private/tmp/test/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/private/tmp/test/node_modules/hexo-renderer-ejs/index.js:5:14)
    at Hexo.tryCatcher (/private/tmp/test/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/private/tmp/test/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /private/tmp/test/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/private/tmp/test/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/private/tmp/test/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/private/tmp/test/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/private/tmp/test/node_modules/hexo/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/private/tmp/test/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/private/tmp/test/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/private/tmp/test/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```
后来发现，在 `source/` 中包含后缀为htm，html的任意内容文件均会得到此错误。
使用其他主题时没有问题，估计是主题的问题吧。

---
回头又看到了 #7 ，大概跟那个出错原因差不多，文件内容或者说格式的问题。默认hello-world的front matter里确实少了最开头的三个 `---` ，不过希望作者至少能给个……友好一点的错误提示吧？

**Comment by ttimasdf** [comment]
这个坑超级隐蔽啊摔！谁曾想会因为*一个html*整个程序就炸了！还是一个超级没有存在感的~~一点卵用没有的~~文件。。。

**Comment by wzpan** [comment]
问题应该已修复。请更新下主题验证下。

**Comment by ttimasdf** [comment]
已修复。好棒
